# https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
language: python
python:
  - 3.6
before_install:
  - python --version
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
# command to run tests
script: # run tests
  - pytest # or py.test for Python version 3.5 and below
after_success:
  - codecov # submit coverage