# https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
language: python
python:
  - 3.9
before_install:
  - python --version
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
# command to run tests
script: # run tests
  - pytest --cov-report term --cov Python3/
after_success:
  - codecov # submit coverage